name: 0pirate Code Review

on:
  pull_request:
    types: [opened, synchronize]

permissions:
  pull-requests: write

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Sleek Repo
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Checkout 0pirate Action Code
        uses: actions/checkout@v4
        with:
          repository: Arunmadhavan28/0pirate-action
          path: 0pirate-action

      - name: Run 0pirate Security Review
        uses: ./0pirate-action
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }} # <-- This is the new, correct name
          opirate-action-token: ${{ secrets.OPIRATE_ACTION_TOKEN }}
          opirate-api-key-name: ${{ secrets.OPIRATE_API_KEY_NAME }}
