name: 0pirate Code Review

on:
  pull_request:
    types: [opened, synchronize]

permissions:
  pull-requests: write

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Check out the main 'sleek' repository's code
      - name: Checkout Sleek Repo
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      # Step 2: Check out your '0pirate-action' repository
      - name: Checkout 0pirate Action Code
        uses: actions/checkout@v4
        with:
          repository: Arunmadhavan28/0pirate-action
          path: 0pirate-action

      # Step 3: Run the action (now using the V2 token)
      - name: Run 0pirate Security Review
        uses: ./0pirate-action
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          opirate-action-token: ${{ secrets.OPIRATE_ACTION_TOKEN_V2 }}
          opirate-api-key-name: ${{ secrets.OPIRATE_API_KEY_NAME }}
          opirate-api-url: ${{ secrets.OPIRATE_API_URL }}
          opirate-provider: ${{ secrets.OPIRATE_PROVIDER }}
          opirate-model: ${{ secrets.OPIRATE_MODEL }}

